name: Assets CI
on:
  push:
    branches: [ main ] 
    # paths:
    # - 'src/assets/**'
  # pull_request:
  #   branches:
  #   - main
  #   paths:
  #   - 'src/assets/**'
  #   - 'images/**'
  # workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Set up QEMU
    #   id: qemu
    #   uses: docker/setup-qemu-action@v2
    #   with:
    #     image: tonistiigi/binfmt:latest
    #     platforms: all

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
        
    # - name: Build container image
    #   run: |
    #     scripts/build-image.sh -s assets -t ci --actions-cache

    - name: Build and push the tagged docker image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO_assets}}
        IMAGE_TAG: latest
      run: |
       cd src/assets
       docker build -t demo_assets .
       docker tag demo_assets:latest public.ecr.aws/p6l7g7u8/demo_assets:latest
       docker push public.ecr.aws/p6l7g7u8/demo_assets:latest

